############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
weight = 4
name = "Our Team"
url = "authors/"

[[main]]
 weight = 4
name = "Posts"
url = "blog/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 3