baseURL: https://www.keydoo-software.com
title: Keydoo Software
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: 'G-JRGGJ7X1G7'

params:
  image: /images/banner.png
  logo: logo-square.png
  subtitle: Two brothers creating indie titles.
  copyright: All rights reserved.
  author: Keydoo Software # todo: set your full name.
  dontShowSource: false
  dontShowLogo: false # If you want to hide the logo, this is what you set to true
  portfolio:
    columns:
      desktop:
        default: 2
      mobile:
        default: 1
  socials:
    # todo: add your social accounts.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:team@keydoo-software.com'
      landing: true
  homepage: "/games"
  bypassWelcomePage: true # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableWelcomePageBackground: false # disables the background image on the homepage
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

permalinks:
  work: ":filename/"

menu:
  main:
    - name: games
      url: /games/
      weight: 1
